# Online Config Subscribe
# Clash For Termux
# Credits [fyn170](https://github.com/fyn170/Clash-Termux)
---
port: 7890
socks-port: 7891
#redir-port: 7892
mixed-port: 7893
#tproxy-port: 7895
mode: rule
log-level: info
ipv6: false
allow-lan: true
unified-delay: true
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: dashboard
tcp-concurrent: false
secret: ""
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 8.8.4.4
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter: []
  nameserver:
    - 1.1.1.1
  fallback: []
  fallback-filter:
    geoip: false 
    geoip-code: 'ID'
    geosite: []
    domain: []
    ipcidr: []
tun:
  enable: false
  stack: system
  dns-hijack: ['any:53', 'tcp://any:53']
  auto-route: true
  auto-detect-interface: true
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  port-whitelist: []
  skip-domain: []
  force-domain: []
iptables: {enable: false, inbound-interface: "lo", bypass: []}
interface-name: ""
enable-process: false
profile: {store-selected: true, store-fake-ip: false}
proxy-providers:
  Server:
    type: file
    behavior: classical
    path: "./akun/akun.yaml"
    health-check:
      enable: true
      interval: 99
      url: http://www.gstatic.com/generate_204
    interval: "300"
proxy-groups:
- name: 18+
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: ADS
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  - Server
- name: Server
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Server
  url: http://www.gstatic.com/generate_204
  interval: '300'
rules:
  - DOMAIN-KEYWORD,18+,Server
  - DOMAIN-SUFFIX,Ads,ADS
  - DOMAIN-KEYWORD,Direct,DIRECT
  - DOMAIN-KEYWORD,Gaming,Server
  - DOMAIN-KEYWORD,Sosmed,Server
  - DOMAIN-KEYWORD,Stream,Server
  - MATCH,GLOBAL
rule-providers:
  18+:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/ClashTermux/main/rule/saru.yaml"
    path: "./rule/saru.yaml"
    inteval: "86400"
  Ads:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/ClashTermux/main/rule/ads.yaml"
    path: "./rule/ads.yaml"
    interval: "86400"
  Direct:
    type: file
    behavior: classical
    path: "./rule/direct.yaml"
    interval: "300"
  Gaming:
    type: file
    behavior: classical
    path: "./rule/gaming.yaml"
    inteval: "300"
  Sosmed:
    type: file
    behavior: classical
    path: "./rule/sosmed.yaml"
    interval: "300"
  Stream:
    type: file
    behavior: classical
    path: "./rule/gaming.yaml"
    inteval: "300"
